### ISSUE TITLE
Reph not working as expected in Lohit2 Oriya

### ISSUE THREAD

**Issue by pravins** [pravins/lohit2#28]
ର୍କ	ର୍ଖ	ର୍ଗ	ର୍ଘ	ର୍ଚ	ର୍ଚ୍ଚ	ର୍ଚ୍ଛ	ର୍ଛ	ର୍ଜ	ର୍ଝ	ର୍ଟ	ର୍ଠ	ର୍ଡ	ର୍ଢ	ର୍ଣ	ର୍ତ	ର୍ତ୍ତ	ର୍ତ    ର୍ଥ	ର୍ଦ	ର୍ଦ୍ଦ	ର୍ଦ୍ଧ	ର୍ଧ	ର୍ନ	ର୍ପ	ର୍ଫ	ର୍ବ	ର୍ଭ	ର୍ମ	ର୍ଯ	ର୍ଯ୍ଯ	ର୍ଶ	ର୍ଷ	ର୍ସ	ର୍ହ	ର୍ଡ଼	ର୍ଢ଼	

![Uploading lohit2-oriya.png . . .]()

**Comment by pravins** [comment]
![lohit2-oriya](https://cloud.githubusercontent.com/assets/56178/5801080/0596201a-a00d-11e4-9e49-d8614ccf60a7.png)

**Comment by ShilpaGite** [comment]
Issue is resolved.

![screenshot from 2015-01-29 17 04 29](https://cloud.githubusercontent.com/assets/8446171/5956942/0efe4af0-a7d9-11e4-84f6-d02465b32d80.png)
