### ISSUE TITLE
[Odia] dot merging with below base part

### ISSUE THREAD

**Issue by pravins** [pravins/lohit2#30]
ଡ଼ୁ	ଡ଼ୂ	ଡ଼ୃ	ଡ଼େ
![lohit2-odia-dot-merging](https://cloud.githubusercontent.com/assets/56178/5801204/8d4561a0-a00e-11e4-9c6a-e6c7d046b249.png)

**Comment by pravins** [comment]
Few more  ଢ଼ୁ	ଢ଼ୂ	ଢ଼ୃ	Will consult with expert.
![merge2](https://cloud.githubusercontent.com/assets/56178/5801240/dfdb1748-a00e-11e4-9860-92c2b628902d.png)

**Comment by ShilpaGite** [comment]
please check if any modification is required for positioning 
https://shilpagite.fedorapeople.org/Lohit-Oriya.ttf

**Comment by ShilpaGite** [comment]
Fixed issue.

![screenshot from 2015-01-29 17 13 49](https://cloud.githubusercontent.com/assets/8446171/5957045/56ce07d4-a7da-11e4-9466-b867ca603acc.png)
