### ISSUE TITLE
does lohit bengali support ৰ

### ISSUE THREAD

**Issue by Shreeshrii** [pravins/lohit2#34]
I would like to use ৰ as mapping for devanagari ba when using bengali font, instead of ব va.

Please let me know whether this is supported by Lohit Bengali font.

Example page: http://sanskritdocuments.org/doc_devii/dkavach.html?lang=bn

**Comment by pravins** [comment]
Still not clear with issue. Please elaborate.
What changes required in font?

**Comment by Shreeshrii** [comment]
Bengali lacks the letter for /va/. Same letter is used for both va and ba.

So, I was looking for options for letters which could be used for representing devanagari /va/ in bengali script.

ৰ looks similar to devanagari /ba/, but as I checked further, I see that it is used for assamese /ra/ so the conjuncts etc won't work, for using as /ba/.

Another option, being used by Aksharamukaha conversion is to use Assamese ৱ to represent devanagari  /va/ and use the bengali /ba/ as equivalent for devanagari /ba/

 I would like to have some distinction between ba and va when transliterated in bengali script, but .I am not sure what the right solution is. 

Probably need input from native bengali speakers regarding this.

**Comment by pravins** [comment]
Mixing of scripts will not work. Even if i add Devanagari "va" into Bengali font, it will not form conjucts with Bengali Virama. 
You are dealing with really tricky stuff :) 
I think you should ask this on Uniocde mailing list, they can provide some hint on this.

**Comment by Shreeshrii** [comment]
Please see http://unicode.org/charts/PDF/U0980.pdf

Additions for Assamese
09F0 ৰ BENGALI LETTER RA WITH MIDDLE DIAGONAL
= Assamese letter ra
09F1 ৱ BENGALI LETTER RA WITH LOWER DIAGONAL
= Assamese letter wa
= bengali letter va with lower diagonal (1.0)

So looks like unicode is actually defining 09F1 ৱ as bengali va

My font question then is, would Lohit Bengali support this?

**Comment by pravins** [comment]
We do have U+09F0 and U+09F1 in Lohit Bengali.

**Comment by pravins** [comment]
Can we close this issue now?

**Comment by Shreeshrii** [comment]
Thanks! Yes, please close.

I have modified the site to use Lohit-Bengali font.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by pravins** [comment]
thats great. Thank you.
